unit uTWPPConnect.ChatList;

// *************************************************
// Generated By: JsonToDelphiClass - 0.65
// Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
// Generated On: 2022-10-27 21:17:49
// *************************************************
// Created By  : Petar Georgiev - 2014
// WebSite     : http://pgeorgiev.com
// *************************************************

interface

uses Generics.Collections, Rest.Json, uTWPPConnect.Classes;

type

  TIdClass = class(TClassPadrao)
  private
    F_serialized: String;
    FFromMe: Boolean;
    FId: String;
    FRemote: String;
  public
    property _serialized: String read F_serialized write F_serialized;
    property fromMe: Boolean read FFromMe write FFromMe;
    property id: String read FId write FId;
    property remote: String read FRemote write FRemote;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TIdClass;
  end;

  TMsgsClass = class(TClassPadrao)
  private
    FAck: Extended;
    FBody: String;
    FFrom: String;
    FHasReaction: Boolean;
    FId: TIdClass;
    FInvis: Boolean;
    FIsAvatar: Boolean;
    FIsDynamicReplyButtonsMsg: Boolean;
    FIsForwarded: Boolean;
    FIsFromTemplate: Boolean;
    FIsMdHistoryMsg: Boolean;
    FIsVcardOverMmsDocument: Boolean;
    FKicNotified: Boolean;
    FLabels: TArray<String>;
    FLastPlaybackProgress: Extended;
    FMentionedJidList: TArray<String>;
    FPollInvalidated: Boolean;
    FPollOptions: TArray<String>;
    FProductHeaderImageRejected: Boolean;
    FPttForwardedFeaturesEnabled: Boolean;
    FRequiresDirectConnection: Boolean;
    FRowId: Extended;
    FSelf: String;
    FStar: Boolean;
    FStickerSentTs: Extended;
    FT: Extended;
    FTo: String;
    FType: String;
    FisNewMsg: Boolean;
  public
    property ack: Extended read FAck write FAck;
    property body: String read FBody write FBody;
    property from: String read FFrom write FFrom;
    property hasReaction: Boolean read FHasReaction write FHasReaction;
    property id: TIdClass read FId write FId;
    property invis: Boolean read FInvis write FInvis;
    property isAvatar: Boolean read FIsAvatar write FIsAvatar;
    property isDynamicReplyButtonsMsg: Boolean read FIsDynamicReplyButtonsMsg
      write FIsDynamicReplyButtonsMsg;
    property isForwarded: Boolean read FIsForwarded write FIsForwarded;
    property isFromTemplate: Boolean read FIsFromTemplate write FIsFromTemplate;
    property isMdHistoryMsg: Boolean read FIsMdHistoryMsg write FIsMdHistoryMsg;
    property isNewMsg: Boolean read FisNewMsg write FisNewMsg;
    property isVcardOverMmsDocument: Boolean read FIsVcardOverMmsDocument
      write FIsVcardOverMmsDocument;
    property kicNotified: Boolean read FKicNotified write FKicNotified;
    property labels: TArray<String> read FLabels write FLabels;
    property lastPlaybackProgress: Extended read FLastPlaybackProgress
      write FLastPlaybackProgress;
    property mentionedJidList: TArray<String> read FMentionedJidList
      write FMentionedJidList;
    property pollInvalidated: Boolean read FPollInvalidated
      write FPollInvalidated;
    property pollOptions: TArray<String> read FPollOptions write FPollOptions;
    property productHeaderImageRejected: Boolean
      read FProductHeaderImageRejected write FProductHeaderImageRejected;
    property pttForwardedFeaturesEnabled: Boolean
      read FPttForwardedFeaturesEnabled write FPttForwardedFeaturesEnabled;
    property requiresDirectConnection: Boolean read FRequiresDirectConnection
      write FRequiresDirectConnection;
    property rowId: Extended read FRowId write FRowId;
    property self: String read FSelf write FSelf;
    property star: Boolean read FStar write FStar;
    property stickerSentTs: Extended read FStickerSentTs write FStickerSentTs;
    property t: Extended read FT write FT;
    property &to : String read FTo write FTo;
    property &type: String read FType write FType;
    destructor Destroy; override;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TMsgsClass;
  end;

  TTcTokenClass = class(TClassPadrao)
  private
  public
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TTcTokenClass;
  end;

  TLastReceivedKeyClass = class(TClassPadrao)
  private
    F_serialized: String;
    FFromMe: Boolean;
    FId: String;
    FRemote: String;
  public
    property _serialized: String read F_serialized write F_serialized;
    property fromMe: Boolean read FFromMe write FFromMe;
    property id: String read FId write FId;
    property remote: String read FRemote write FRemote;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TLastReceivedKeyClass;
  end;

  TChatListClass = class(TClassPadrao)
  private
    FArchiveAtMentionViewedInDrawer: Boolean;
    FDisappearingModeInitiator: String;
    FEndOfHistoryTransferType: Extended;
    FEphemeralDuration: Extended;
    FHasChatBeenOpened: Boolean;
    FHasUnreadMention: Boolean;
    FId: String;
    FIsReadOnly: Boolean;
    FLabels: TArray<String>;
    FLastReceivedKey: TLastReceivedKeyClass;
    FMsgs: TArray<TMsgsClass>;
    FMuteExpiration: Extended;
    FNotSpam: Boolean;
    FPendingInitialLoading: Boolean;
    FPendingMsgs: Boolean;
    FT: Extended;
    FTcToken: TTcTokenClass;
    FTcTokenTimestamp: Extended;
    FUnreadCount: Extended;
    FUnreadMentionCount: Extended;
    FUnreadMentionsOfMe: TArray<String>;
  public
    property archiveAtMentionViewedInDrawer: Boolean
      read FArchiveAtMentionViewedInDrawer
      write FArchiveAtMentionViewedInDrawer;
    property disappearingModeInitiator: String read FDisappearingModeInitiator
      write FDisappearingModeInitiator;
    property endOfHistoryTransferType: Extended read FEndOfHistoryTransferType
      write FEndOfHistoryTransferType;
    property ephemeralDuration: Extended read FEphemeralDuration
      write FEphemeralDuration;
    property hasChatBeenOpened: Boolean read FHasChatBeenOpened
      write FHasChatBeenOpened;
    property hasUnreadMention: Boolean read FHasUnreadMention
      write FHasUnreadMention;
    property id: String read FId write FId;
    property isReadOnly: Boolean read FIsReadOnly write FIsReadOnly;
    property labels: TArray<String> read FLabels write FLabels;
    property lastReceivedKey: TLastReceivedKeyClass read FLastReceivedKey
      write FLastReceivedKey;
    property msgs: TArray<TMsgsClass> read FMsgs write FMsgs;
    property muteExpiration: Extended read FMuteExpiration
      write FMuteExpiration;
    property notSpam: Boolean read FNotSpam write FNotSpam;
    property pendingInitialLoading: Boolean read FPendingInitialLoading
      write FPendingInitialLoading;
    property pendingMsgs: Boolean read FPendingMsgs write FPendingMsgs;
    property t: Extended read FT write FT;
    property tcToken: TTcTokenClass read FTcToken write FTcToken;
    property tcTokenTimestamp: Extended read FTcTokenTimestamp
      write FTcTokenTimestamp;
    property unreadCount: Extended read FUnreadCount write FUnreadCount;
    property unreadMentionCount: Extended read FUnreadMentionCount
      write FUnreadMentionCount;
    property unreadMentionsOfMe: TArray<String> read FUnreadMentionsOfMe
      write FUnreadMentionsOfMe;
    destructor Destroy; override;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TChatListClass;
  end;

  TResultClass = class(TClassPadraoList<TItemClass>)
  private
    FChatList: TArray<TChatListClass>;
  public
    property ChatList: TArray<TChatListClass> read FChatList write FChatList;
    destructor Destroy; override;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TResultClass;
  end;

  TChatsList = class(TClassPadraoList<TResultClass>)
  private
    FName: String;
    FResult: TResultClass;
  public
    property name: String read FName write FName;
    property result: TResultClass read FResult write FResult;
    destructor Destroy; override;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TChatsList;
  end;

implementation

{ TIdClass }

function TIdClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TIdClass.FromJsonString(AJsonString: string): TIdClass;
begin
  result := TJson.JsonToObject<TIdClass>(AJsonString)
end;

{ TMsgsClass }

destructor TMsgsClass.Destroy;
begin
  FId.free;
  inherited;
end;

function TMsgsClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TMsgsClass.FromJsonString(AJsonString: string): TMsgsClass;
begin
  result := TJson.JsonToObject<TMsgsClass>(AJsonString)
end;

{ TTcTokenClass }

function TTcTokenClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TTcTokenClass.FromJsonString(AJsonString: string): TTcTokenClass;
begin
  result := TJson.JsonToObject<TTcTokenClass>(AJsonString)
end;

{ TLastReceivedKeyClass }

function TLastReceivedKeyClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TLastReceivedKeyClass.FromJsonString(AJsonString: string)
  : TLastReceivedKeyClass;
begin
  result := TJson.JsonToObject<TLastReceivedKeyClass>(AJsonString)
end;

{ TChatListClass }


destructor TChatListClass.Destroy;
var
  LmsgsItem: TMsgsClass;
begin

  for LmsgsItem in FMsgs do
    LmsgsItem.free;

  FLastReceivedKey.free;
  FTcToken.free;
  inherited;
end;

function TChatListClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TChatListClass.FromJsonString(AJsonString: string)
  : TChatListClass;
begin
  result := TJson.JsonToObject<TChatListClass>(AJsonString)
end;

{ TResultClass }

destructor TResultClass.Destroy;
var
  LchatListItem: TChatListClass;
begin

  for LchatListItem in FChatList do
    LchatListItem.free;

  inherited;
end;

function TResultClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TResultClass.FromJsonString(AJsonString: string): TResultClass;
begin
  result := TJson.JsonToObject<TResultClass>(AJsonString)
end;

{ TRootClass }


destructor TChatsList.Destroy;
begin
  FResult.free;
  inherited;
end;

function TChatsList.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TChatsList.FromJsonString(AJsonString: string): TChatsList;
begin
  result := TJson.JsonToObject<TChatsList>(AJsonString)
end;

end.
