{####################################################################################################################
  License
  Copyright 2022 WPPConnect Team https://wppconnect-team.github.io/

  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance
  with the License. You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
  an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
  specific language governing permissions and limitations under the License.

                              WPPCONNECT - Componente de comunicação (Não Oficial)
                                           https://wppconnect-team.github.io/
                                            Maio de 2022
####################################################################################################################}

unit u_Retorno_SendFileMensagem;

//  *************************************************
//    Generated By: JsonToDelphiClass - 0.65
//    Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
//    Generated On: 2022-05-30 23:25:57
//  *************************************************
//    Created By  : Petar Georgiev - 2014
//    WebSite     : http://pgeorgiev.com
//  *************************************************

interface

uses Generics.Collections, Rest.Json;

type

TSendMsgResultClass = class
private
  F_flags: Extended;
  F_resolveLevel: Extended;
  F_value: String;
public
  property _flags: Extended read F_flags write F_flags;
  property _resolveLevel: Extended read F_resolveLevel write F_resolveLevel;
  property _value: String read F_value write F_value;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TSendMsgResultClass;
end;

TResultClass = class
private
  FAck: Extended;
  FId: String;
  FSendMsgResult: TSendMsgResultClass;
public
  property ack: Extended read FAck write FAck;
  property id: String read FId write FId;
  property sendMsgResult: TSendMsgResultClass read FSendMsgResult write FSendMsgResult;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TResultClass;
end;

TRetorno_SendFileMensagemClass = class
private
  FResult: TResultClass;
public
  property result: TResultClass read FResult write FResult;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TRetorno_SendFileMensagemClass;
end;

implementation

{TSendMsgResultClass}


function TSendMsgResultClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TSendMsgResultClass.FromJsonString(AJsonString: string): TSendMsgResultClass;
begin
  result := TJson.JsonToObject<TSendMsgResultClass>(AJsonString)
end;

{TResultClass}

constructor TResultClass.Create;
begin
  inherited;
  FSendMsgResult := TSendMsgResultClass.Create();
end;

destructor TResultClass.Destroy;
begin
  FSendMsgResult.free;
  inherited;
end;

function TResultClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TResultClass.FromJsonString(AJsonString: string): TResultClass;
begin
  result := TJson.JsonToObject<TResultClass>(AJsonString)
end;

{TRetorno_SendFileMensagemClass}

constructor TRetorno_SendFileMensagemClass.Create;
begin
  inherited;
  FResult := TResultClass.Create();
end;

destructor TRetorno_SendFileMensagemClass.Destroy;
begin
  FResult.free;
  inherited;
end;

function TRetorno_SendFileMensagemClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TRetorno_SendFileMensagemClass.FromJsonString(AJsonString: string): TRetorno_SendFileMensagemClass;
begin
  result := TJson.JsonToObject<TRetorno_SendFileMensagemClass>(AJsonString)
end;

end.
